version: "3.8"

services:
  postgres-db:
    image: postgres:15.6
    container_name: tesloc
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: ${DB_TZ}
      PGTZ: ${DB_TZ}
    volumes:
      - ./postgres:/var/lib/postgresql/data:z
    ports:
      - 5432:5432